### DISCUSSION TITLE
分开使用docker-compose部署成功经验分享

### DISCUSSION THREAD

**Discussion by quewen08** [oddfar/campus-imaotai#174] [分享部署教程]
#### 部署mysql

```yml
version: '3'

networks:
  mysql57:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.23
    container_name: mysql57
    # 重启
    restart: always
    # 提供伪终端
    tty: true
    ports:
      - 3306:3306
    # root具备管理员权限
    privileged: true
    environment:
      # root 密码
      MYSQL_ROOT_PASSWORD: 123456789
      TZ: Asia/Shanghai
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: 'campus_imaotai'
    volumes:    
      # 配置挂载，这里目录可以随意指定，左侧为宿主机目录，右侧为docker容器内目录文件
      - /usr/docker-vol/mysql57/etc/my.cnf:/etc/my.cnf
      - /usr/docker-vol/mysql57/etc:/var/run/mysqld
      # 数据挂载
      - /usr/docker-vol/mysql57/data/:/var/lib/mysql/
      # 方便测试可不挂载
      - /usr/bin:/usr/bin
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          i'--lower-case-table-names=1'
        ]
    networks:
      - mysql57
```

这里贴出我的mysql配置文件`my.cnf`
```conf
[mysqld]
port=3306
skip-host-cache
skip-name-resolve
pid-file        = /var/run/mysqld/mysqld.pid  # pid文件所在目录
socket          = /var/run/mysqld/mysqld.sock # 用于本地连接的socket套接字
datadir         = /var/lib/mysql              # 数据文件存放的目录
secure-file-priv=NULL
max_connections = 10240
max_connect_errors = 256
max_allowed_packet = 128M
interactive_timeout = 600
wait_timeout = 600
back_log = 230
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
#####################用户进程分配到的内存设置BEGIN#############################
#建议先调整为2M，后期观察调整
sort_buffer_size = 2097152
#一般数据库中没什么大的事务，设成1~2M，默认32kb
binlog_cache_size = 1048576

#explicit_defaults_for_timestamp=true
#数据库错误日志文件
#log_error = error.log
general_log = 1
general_log_file = /var/lib/mysql/logs/mysql.log
#慢查询sql日志设置
slow_query_log = 1
slow_query_log_file = slow.log
#log_queries_not_using_indexes = 1
log_slow_slave_statements = 1
long_query_time = 1
default-storage-engine = InnoDB

# 开启二进制日志功能 & 日志位置存放位置`/var/lib/mysql`
#log-bin=mysql-bin
#log-bin=/var/lib/mysql/mysql-bin
# binlog格式
# 1. STATEMENT：基于SQL语句的模式，binlog 数据量小，但是某些语句和函数在复制过程可能导致数据不一致甚至出错；
# 2. MIXED：混合模式，根据语句来选用是 STATEMENT 还是 ROW 模式；
# 3. ROW：基于行的模式，记录的是行的完整变化。安全，但 binlog 会比其他两种模式大很多；
binlog_format=ROW
# FULL：binlog记录每一行的完整变更 MINIMAL：只记录影响后的行
#binlog_row_image=FULL
# 日志文件大小
# max_binlog_size=1G
max_binlog_size=100M
# 定义清除过期日志的时间(这里设置为7天)
expire_logs_days=7

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

#Custom config should go here
!includedir /etc/mysql/conf.d/
```

#### 部署redis

_我因为是直接安装在宿主机的redis，这边就复制下项目里的redis配置文件。道理相通。_

```yml
version: '3'

networks:
  redis:
    driver: bridge

services:
  redis:
    image: redis:6.2.12
    container_name: redis
    volumes:
      # 配置文件
      - /docker/redis/conf:/redis/config
      # 数据文件
      - /docker/redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    network_mode: "host"
    networks:
      - redis
```

#### 部署campus-imaotai

```yml
version : '3'

networks:
  mysql57:
    external:
      # 这里的name，你需要自己去查一下生成后的名称，可能不一样
      name: mysql57_mysql57
  redis:
    external:
      # 这里的name，你需要自己去查一下生成后的名称，可能不一样
      name: redis_redis

services:
  campus-server:
    image: oddfar/campus-imaotai
    container_name: campus-imaotai
    ports:
      - 8196:8196
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8196
      spring.config.additional-location: /home/campus/conf/application-prod.yml
    volumes:
      - /data/campus-imaotai/server/conf:/home/campus/conf
      # 方便调试可不挂载
      - /usr/bin:/usr/bin
    privileged: true
    # 重启
    restart: always
    # 提供伪终端
    tty: true
    networks:
      - mysql57
      - redis
```

这里放一下我本地的`application-prod.yml`

**需要注意的地方**
- 主库的ip地址，需要查看网卡或者容器对应的网卡地址
- redis的ip地址也是一样的，需要查看网卡对应的地址

> 查看ip的方式为在宿主机中输入以下命令

```cmd
docker inspect 容器名称
```

```yml
--- # 数据源配置
spring:
  #数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: false
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://172.22.0.2:3306/campus_imaotai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=false&allowPublicKeyRetrieval=false
          username: root
          password: 123456789
        # 从库数据源
      #        slave:
      #          lazy: true
      #          type: ${spring.datasource.type}
      #          driverClassName: com.mysql.cj.jdbc.Driver
      #          url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      #          username: root
      #          password: 123456789
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟，这里需要修改一下，否则系统会停止运行
        maxLifetime: 800000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1
        # 多久检查一次连接的活性
        keepaliveTime: 30000


--- # redis
spring:
  redis:
    # 地址
    host: 172.22.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    # password:
    # 连接超时时间
    timeout: 10s

```

#### 编译前端

```cmd
npm i && npm run build:prod
```

将打包好的`dist`文件夹放在宿主机任何目录即可  如 `/www/campus-imaotai`

#### 部署nginx 

**我是直接源码编译安装的，因为要提供其他环境使用，还要安装其他插件，没有使用docker**

```yml
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # https配置参考 start
        #listen       443 ssl;

        # 证书直接存放 /docker/nginx/cert/ 目录下即可 更改证书名称即可 无需更改证书路径
        #ssl on;
        #ssl_certificate      /etc/nginx/cert/xxx.local.crt; # /etc/nginx/cert/ 为docker映射路径 不允许更改
        #ssl_certificate_key  /etc/nginx/cert/xxx.local.key; # /etc/nginx/cert/ 为docker映射路径 不允许更改
        #ssl_session_timeout 5m;
        #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        #ssl_prefer_server_ciphers on;
        # https配置参考 end

	location / {
            # 这里我直接使用上面打包好之后放置的目录，保证root下必须有index.html文件即可
            root   /www/campus-imaotai/dist;
	    try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }

        location /prod-api/{
	        proxy_set_header Host $http_host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header REMOTE-HOST $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_pass http://127.0.0.1:8160/;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
```

#### 访问

到此大功告成，其中有出入的地方我都写在注释里面了，而且这种部署方式可以兼容其他软件同时部署，不会说当前的环境只能用一次
