### ISSUE TITLE
分享下自己docker部署经验

### ISSUE THREAD

**Issue by arvinws** [oddfar/campus-imaotai#167]
**后端使用docker在服务器运行的**
按文档https://oddfar.github.io/campus-doc/pages/8f2aa8/#%E5%90%AF%E5%8A%A8
![image](https://github.com/oddfar/campus-imaotai/assets/43133223/d4d2dd74-a9c9-4338-81ad-9b79fd9b59ff)
这里有一点小问题，指定网络的话，你的mysql和redis容器也要在同一个网络中， 可以不指定。
然后在连接数据库配置的时候，填写mysql,redis容器统一的网关ip:port
![image](https://github.com/oddfar/campus-imaotai/assets/43133223/227b69f3-07a7-46c5-a03d-468ee0a99014)
**前端**
前端是本地编译代码调用接口
1. 代码git下来
2. 打开vscode
3. 打开vue_campus_admin目录
4. 打开vue.config.js文件
5. 找到process.env.VUE_APP_BASE_API
6. 修改成部署好的后端接口地址，保存

在vue_campus_admin根目录用终端运行命令
npm install

npm run dev
编译后本地就可以访问前端了

**前端使用docker** nginx部署

1.docker run -d --restart=always --name="web" -p 8890:80 -v $PWD/dist:/usr/share/nginx/html nginx
2.修改nginx配置，复制项目文档里面就可以了
`
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;
		charset utf-8;

		location / {
            root   /www/wwwroot/xxxxx.com/dist;
			try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }
		
		location /prod-api/ {
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_pass http://localhost:8160/;
		}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
`
proxy_pass http://localhost:8160/;   这里一定要改成后端容器的接口地址，比如后端接口网关ip是172.168.0.1，地址可以修改成http://172.168.0.1:8160/

**Comment by dianjie** [comment]
基于1.0.8更新了一下，下载[1.0.11](https://github.com/oddfar/campus-imaotai/releases/tag/V1.0.11)的`dist.zip`,`campus-modular.jar`

原目录下，删掉 html下的dist目录、jar 下所有文件，把dist压缩包解压到 html文件下、 campus-modular.jar 放置到 jar 目录下，同时在 jar 目录下新建`application-prod.yml`文件，文件内容如下：

```
--- # 数据源配置
spring:
  #数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: false
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://campus-mysql:3306/campus_imaotai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: oddfar_imaotai
        # 从库数据源
      #        slave:
      #          lazy: true
      #          type: ${spring.datasource.type}
      #          driverClassName: com.mysql.cj.jdbc.Driver
      #          url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      #          username: root
      #          password: 123456789
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1
        # 多久检查一次连接的活性
        keepaliveTime: 30000


--- # redis
spring:
  redis:
    # 地址
    host: campus-redis
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: oddfar_imaotai
    # 连接超时时间
    timeout: 10s
````
`campus-dockerfile`文件内容更改如下：

```
# 基础镜像
FROM openjdk:8
#FROM 987846/jdk1.8
# author
MAINTAINER oddfar

# 挂载目录
VOLUME /home/campus
# 创建目录
RUN mkdir -p /home/campus
# 指定路径
WORKDIR /home/campus
# 复制jar文件到路径
COPY ./jar/*.jar /home/campus/campus.jar
COPY ./jar/*.yml /home/campus/application-prod.yml
# 启动应用

ENTRYPOINT ["java", \
            "-Dspring.config.additional-location=./application-prod.yml", \
            "-Dserver.port=8160", \
            "-jar", "campus.jar"]
```
然后执行命令：

1、删除容器：
docker rm -f campus-server campus-nginx
2、删除旧镜像
docker rmi campus-imt-vxxx_campus-server
3、启动项目，项目根目录下执行
docker-compose up -d

我对Docker不熟，目前服务是跑起来了，但不知道对不对。
