### ISSUE TITLE
树莓派容器部署报错

### ISSUE THREAD

**Issue by songyongguo1987** [oddfar/campus-imaotai#54]
ERROR: Service 'campus-mysql' failed to build : no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by oddfar** [comment]
`docker-compose.yml` 文件里
```yml
  campus-mysql:
    container_name: campus-mysql
    image: mysql:5.7
    build:
      context: .
      dockerfile: mysql-dockerfile
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      WAIT_HOSTS: campus-mysql:3306
      MYSQL_DATABASE: 'campus_imaotai'
      MYSQL_ROOT_PASSWORD: oddfar_imaotai
    networks:
      - campus_net
    platform: linux/x86_64
```
 platform: linux/x86_64 这行的注释删掉
